### ISSUE TITLE
Why are they called "recommend" instead of "recommended"?

### ISSUE THREAD

**Issue by parlough** [dart-lang/lints#10]
It seems in the case of the `core` set, "core" is being used as an adjective, implying it's the "core set of rules". 

This makes the `recommend` set stand out to me as strange and a little awkward to say, as it is a verb rather than an adjective or even a noun. I would expect to say "the recommended set of rules" rather than "the recommend set of rules". 

I'm assuming there was internal discussion around this decision, but was hoping to better understand.

**Comment by pq** [comment]
Funny, I just now mis-typed `recommended` in another issue. 😃 

Let's page folks to see how they weigh in.

### **PROPOSAL:**  change `recommend.yaml` to `recommended.yaml` ?

- [ ] @parlough  
- [ ] @pq
- [ ] @mit-mit 
- [ ] @devoncarew 
- [ ] @munificent
- [ ]  @lrhn 
- [ ] @natebosch 
- [ ] @jakemac53 
- [ ] @csells 
- [ ] @goderbauer

**Comment by csells** [comment]
yes please

**Comment by goderbauer** [comment]
I am in favor of the rename (I don’t have sufficient rights in this repository to check my name in the list above, though).

**Comment by pq** [comment]
> I don’t have sufficient rights in this repository to check my name in the list above, though

@kevmoo: can we fix that?

**Comment by kevmoo** [comment]
What am I doing?

**Comment by pq** [comment]
> What am I doing?

Adding @goderbauer to the `dart-lang` org? 🙏   (Will follow-up separately...)
