### ISSUE TITLE
Remove to-be-deprecated rules `iterable_contains_unrelated_type` and `list_remove_unrelated_type`

### ISSUE THREAD

**Issue by srawlins** [dart-lang/lints#118]
These two rules will be deprecated (in https://github.com/dart-lang/linter/issues/3893) in favor of [`collection_methods_unrelated_type`](https://dart-lang.github.io/linter/lints/collection_methods_unrelated_type.html), which I'd also like to add to package:lints (https://github.com/dart-lang/lints/issues/93).

**Comment by devoncarew** [comment]
What SDK version would the rules be deprecated in (and the new rule be available)?

**Comment by srawlins** [comment]
Dart 3.1 at the earliest. The new rule is available in Dart 2.19.0.

I'm not sure whether the right practice is to deprecate (which results in new diagnostics in `analysis_options.yaml` files) first or to remove from package:lints first.

**Comment by devoncarew** [comment]
Hmm, from a previous discussion in this repo, I believe that the deprecations wouldn't show as diagnostics for users? Since the user's analysis options file would reference this one. So we likely have a freer hand wrt timing here (esp. as this package already has a lower bounds of `3.0.0-417`).

**Comment by srawlins** [comment]
The rules are now deprecated and should be removed from this repo.

**Comment by devoncarew** [comment]
Removals approved.
