### ISSUE TITLE
document what lints have corresponding automated fixes

### ISSUE THREAD

**Issue by pq** [dart-lang/lints#12]
Two items really.

1. we should document corresponding lints
2. we should add ones where possible (and identify lints that are not fixable w/o intervention)

Below is a quick run of a tool in the linter repo.  

✅ signifies something we have a fix for
➖ signals that we think this is not auto-fixable
🤔 we should consider it

(fyi @goderbauer @bwilkerson)
## Core Lints

| name | fix | bulk |
| :--- | :---: | :---:  |
|  [`avoid_empty_else`](https://dart-lang.github.io/linter/lints/avoid_empty_else.html) | ✅ | ✅ |
|  [`avoid_relative_lib_imports`](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html) | ✅ | ✅ |
|  [`avoid_shadowing_type_parameters`](https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html) | ➖ | ➖ |
|  [`avoid_types_as_parameter_names`](https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html) | ➖ | ➖ |
|  [`await_only_futures`](https://dart-lang.github.io/linter/lints/await_only_futures.html) | ✅ | ✅ |
|  [`camel_case_extensions`](https://dart-lang.github.io/linter/lints/camel_case_extensions.html) | ➖ | ➖ |
|  [`camel_case_types`](https://dart-lang.github.io/linter/lints/camel_case_types.html) | ➖ | ➖ |
|  [`curly_braces_in_flow_control_structures`](https://dart-lang.github.io/linter/lints/curly_braces_in_flow_control_structures.html) | ✅ | ✅ |
|  [`empty_catches`](https://dart-lang.github.io/linter/lints/empty_catches.html) | ✅ | ✅ |
|  [`file_names`](https://dart-lang.github.io/linter/lints/file_names.html) | ➖ | ➖ |
|  [`hash_and_equals`](https://dart-lang.github.io/linter/lints/hash_and_equals.html) | ✅ | ✅ |
|  [`iterable_contains_unrelated_type`](https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html) | ➖ | ➖ |
|  [`list_remove_unrelated_type`](https://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html) | ➖ | ➖ |
|  [`no_duplicate_case_values`](https://dart-lang.github.io/linter/lints/no_duplicate_case_values.html) | ✅ | ✅ |
|  [`non_constant_identifier_names`](https://dart-lang.github.io/linter/lints/non_constant_identifier_names.html) | ✅ | ✅ |
|  [`package_prefixed_library_names`](https://dart-lang.github.io/linter/lints/package_prefixed_library_names.html) | ➖ | ➖ |
|  [`prefer_generic_function_type_aliases`](https://dart-lang.github.io/linter/lints/prefer_generic_function_type_aliases.html) | ✅ | ✅ |
|  [`prefer_is_empty`](https://dart-lang.github.io/linter/lints/prefer_is_empty.html) | ✅ | ✅ |
|  [`prefer_is_not_empty`](https://dart-lang.github.io/linter/lints/prefer_is_not_empty.html) | ✅ | ✅ |
|  [`prefer_iterable_whereType`](https://dart-lang.github.io/linter/lints/prefer_iterable_whereType.html) | ✅ | ✅ |
|  [`prefer_typing_uninitialized_variables`](https://dart-lang.github.io/linter/lints/prefer_typing_uninitialized_variables.html) | 🤔 | 🤔 |
|  [`provide_deprecation_message`](https://dart-lang.github.io/linter/lints/provide_deprecation_message.html) | ➖ | ➖ |
|  [`unnecessary_overrides`](https://dart-lang.github.io/linter/lints/unnecessary_overrides.html) | ✅ | ✅ |
|  [`unrelated_type_equality_checks`](https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html) | ➖ | ➖ |
|  [`valid_regexps`](https://dart-lang.github.io/linter/lints/valid_regexps.html) | ➖ | ➖ |
|  [`void_checks`](https://dart-lang.github.io/linter/lints/void_checks.html) | ➖ | ➖ |

## Recommended Lints

| name | fix | bulk |
| :--- | :---: | :---:  |
|  [`always_require_non_null_named_parameters`](https://dart-lang.github.io/linter/lints/always_require_non_null_named_parameters.html) | ✅ | ✅ |
|  [`annotate_overrides`](https://dart-lang.github.io/linter/lints/annotate_overrides.html) | ✅ | ✅ |
|  [`avoid_function_literals_in_foreach_calls`](https://dart-lang.github.io/linter/lints/avoid_function_literals_in_foreach_calls.html) | 🤔 | 🤔 |
|  [`avoid_init_to_null`](https://dart-lang.github.io/linter/lints/avoid_init_to_null.html) | ✅ | ✅ |
|  [`avoid_null_checks_in_equality_operators`](https://dart-lang.github.io/linter/lints/avoid_null_checks_in_equality_operators.html) | 🤔 | 🤔 |
|  [`avoid_renaming_method_parameters`](https://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html) | ➖ | ➖ |
|  [`avoid_return_types_on_setters`](https://dart-lang.github.io/linter/lints/avoid_return_types_on_setters.html) | ✅ | ✅ |
|  [`avoid_returning_null_for_void`](https://dart-lang.github.io/linter/lints/avoid_returning_null_for_void.html) | 🤔 | 🤔 |
|  [`avoid_single_cascade_in_expression_statements`](https://dart-lang.github.io/linter/lints/avoid_single_cascade_in_expression_statements.html) | ✅ | ✅ |
|  [`constant_identifier_names`](https://dart-lang.github.io/linter/lints/constant_identifier_names.html) | ➖ | ➖ |
|  [`control_flow_in_finally`](https://dart-lang.github.io/linter/lints/control_flow_in_finally.html) | ➖ | ➖ |
|  [`empty_constructor_bodies`](https://dart-lang.github.io/linter/lints/empty_constructor_bodies.html) | ✅ | ✅ |
|  [`empty_statements`](https://dart-lang.github.io/linter/lints/empty_statements.html) | ✅ | ✅ |
|  [`exhaustive_cases`](https://dart-lang.github.io/linter/lints/exhaustive_cases.html) | 🤔 | 🤔 |
|  [`implementation_imports`](https://dart-lang.github.io/linter/lints/implementation_imports.html) | ➖ | ➖ |
|  [`library_names`](https://dart-lang.github.io/linter/lints/library_names.html) | ➖ | ➖ |
|  [`library_prefixes`](https://dart-lang.github.io/linter/lints/library_prefixes.html) | ➖ | ➖ |
|  [`null_closures`](https://dart-lang.github.io/linter/lints/null_closures.html) | ✅ | ✅ |
|  [`overridden_fields`](https://dart-lang.github.io/linter/lints/overridden_fields.html) | ➖ | ➖ |
|  [`package_names`](https://dart-lang.github.io/linter/lints/package_names.html) | ➖ | ➖ |
|  [`prefer_adjacent_string_concatenation`](https://dart-lang.github.io/linter/lints/prefer_adjacent_string_concatenation.html) | ✅ | ✅ |
|  [`prefer_collection_literals`](https://dart-lang.github.io/linter/lints/prefer_collection_literals.html) | ✅ | ✅ |
|  [`prefer_conditional_assignment`](https://dart-lang.github.io/linter/lints/prefer_conditional_assignment.html) | ✅ | ✅ |
|  [`prefer_contains`](https://dart-lang.github.io/linter/lints/prefer_contains.html) | ✅ | ✅ |
|  [`prefer_equal_for_default_values`](https://dart-lang.github.io/linter/lints/prefer_equal_for_default_values.html) | ✅ | ✅ |
|  [`prefer_final_fields`](https://dart-lang.github.io/linter/lints/prefer_final_fields.html) | ✅ | ✅ |
|  [`prefer_for_elements_to_map_fromIterable`](https://dart-lang.github.io/linter/lints/prefer_for_elements_to_map_fromIterable.html) | ✅ | ✅ |
|  [`prefer_function_declarations_over_variables`](https://dart-lang.github.io/linter/lints/prefer_function_declarations_over_variables.html) | ➖ | ➖ |
|  [`prefer_if_null_operators`](https://dart-lang.github.io/linter/lints/prefer_if_null_operators.html) | ✅ | ✅ |
|  [`prefer_initializing_formals`](https://dart-lang.github.io/linter/lints/prefer_initializing_formals.html) | 🤔 | 🤔 |
|  [`prefer_inlined_adds`](https://dart-lang.github.io/linter/lints/prefer_inlined_adds.html) | ✅ | ✅ |
|  [`prefer_is_not_operator`](https://dart-lang.github.io/linter/lints/prefer_is_not_operator.html) | ✅ | ✅ |
|  [`prefer_null_aware_operators`](https://dart-lang.github.io/linter/lints/prefer_null_aware_operators.html) | ✅ | ✅ |
|  [`prefer_spread_collections`](https://dart-lang.github.io/linter/lints/prefer_spread_collections.html) | ✅ | ✅ |
|  [`prefer_void_to_null`](https://dart-lang.github.io/linter/lints/prefer_void_to_null.html) | 🤔 | 🤔 |
|  [`recursive_getters`](https://dart-lang.github.io/linter/lints/recursive_getters.html) | ➖ | ➖ |
|  [`slash_for_doc_comments`](https://dart-lang.github.io/linter/lints/slash_for_doc_comments.html) | ✅ | ✅ |
|  [`type_init_formals`](https://dart-lang.github.io/linter/lints/type_init_formals.html) | ✅ | ✅ |
|  [`unnecessary_brace_in_string_interps`](https://dart-lang.github.io/linter/lints/unnecessary_brace_in_string_interps.html) | ✅ | ✅ |
|  [`unnecessary_const`](https://dart-lang.github.io/linter/lints/unnecessary_const.html) | ✅ | ✅ |
|  [`unnecessary_getters_setters`](https://dart-lang.github.io/linter/lints/unnecessary_getters_setters.html) | 🤔 | 🤔 |
|  [`unnecessary_new`](https://dart-lang.github.io/linter/lints/unnecessary_new.html) | ✅ | ✅ |
|  [`unnecessary_null_in_if_null_operators`](https://dart-lang.github.io/linter/lints/unnecessary_null_in_if_null_operators.html) | ✅ | ✅ |
|  [`unnecessary_string_escapes`](https://dart-lang.github.io/linter/lints/unnecessary_string_escapes.html) | 🤔 | 🤔 |
|  [`unnecessary_string_interpolations`](https://dart-lang.github.io/linter/lints/unnecessary_string_interpolations.html) | ✅ | ✅ |
|  [`unnecessary_this`](https://dart-lang.github.io/linter/lints/unnecessary_this.html) | ✅ | ✅ |
|  [`use_function_type_syntax_for_parameters`](https://dart-lang.github.io/linter/lints/use_function_type_syntax_for_parameters.html) | ✅ | ✅ |
|  [`use_rethrow_when_possible`](https://dart-lang.github.io/linter/lints/use_rethrow_when_possible.html) | ✅ | ✅ |

## Flutter Lints

| name | fix | bulk |
| :--- | :---: | :---:  |
|  [`avoid_print`](https://dart-lang.github.io/linter/lints/avoid_print.html) | 🤔 | 🤔 |
|  [`avoid_unnecessary_containers`](https://dart-lang.github.io/linter/lints/avoid_unnecessary_containers.html) | 🤔 | 🤔 |
|  [`avoid_web_libraries_in_flutter`](https://dart-lang.github.io/linter/lints/avoid_web_libraries_in_flutter.html) | ➖ | ➖ |
|  [`no_logic_in_create_state`](https://dart-lang.github.io/linter/lints/no_logic_in_create_state.html) | ➖ | ➖ |
|  [`prefer_const_constructors`](https://dart-lang.github.io/linter/lints/prefer_const_constructors.html) | ✅ | ✅ |
|  [`prefer_const_constructors_in_immutables`](https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html) | ✅ | ✅ |
|  [`prefer_const_declarations`](https://dart-lang.github.io/linter/lints/prefer_const_declarations.html) | ✅ | ✅ |
|  [`prefer_const_literals_to_create_immutables`](https://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html) | 🤔 | 🤔 |
|  [`sized_box_for_whitespace`](https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html) | 🤔 | 🤔 |
|  [`use_full_hex_values_for_flutter_colors`](https://dart-lang.github.io/linter/lints/use_full_hex_values_for_flutter_colors.html) | ✅ | ✅ |
|  [`use_key_in_widget_constructors`](https://dart-lang.github.io/linter/lints/use_key_in_widget_constructors.html) | 🤔 | 🤔 |

(UPDATED: 05/05)

**Comment by devoncarew** [comment]
Great to have this documented!

**Comment by bwilkerson** [comment]
See https://github.com/dart-lang/sdk/issues/45932 for ideas on possible fixes for some of the lints.

**Comment by goderbauer** [comment]
Thanks for the list!

I'd love it if the information whether a lint has an auto-fix would be available on https://dart-lang.github.io/linter/lints/index.html. That's where the comments in our templates currently direct people to to learn more about a lint.

**Comment by devoncarew** [comment]
cc @parlough, who's doing work in this area

**Comment by pq** [comment]
@parlough: if you have ideas for how to present this information, I'd be happy to generate an index that you can pull down.  Or maybe this would be something to add to `machine.json`?

**Comment by bwilkerson** [comment]
I've wondered a few time whether we might want to add something to the documentation for the lints (and other diagnostics) to indicate that there are fixes available for them. Perhaps a generated line at the end for the form

Fixable using `dart fix` or in the IDE using '\<fix label\>'.

with support for a list if there's more than one fix.

**Comment by parlough** [comment]
@pq I think an adding it to the machine generated JSON would be easiest as it seems fixes are defined as lint rule -> fixes in the `analysis_server`, but if they are in a separate document that's workable as well.

@bwilkerson What are the fix labels in this case? The values like `dart.fix.remove.unnecessaryStringInterpolation`?

**Comment by bwilkerson** [comment]
I was thinking of using the labels from the UI, such as 'Remove unnecessary string interpolation'. I don't think the internal ids would be meaningful to users.

**Comment by bernaferrari** [comment]
I'm not sure what I want is DIRECTLY related to this issue, but I hate when my IDE turns red and there are no suggestions. Two things come to my mind: missing semicolon and "try removing the 'abstract' keyword" error. These should be very easy fixes as the error message already detects them, and the fix should be "remove a word", "change a word" or "add a word".

**Comment by pq** [comment]
> I hate when my IDE turns red and there are no suggestions

💯 

Please do give us feedback when you see places we've missed.  Those bugs will get tracked on the SDK (https://github.com/dart-lang/sdk/issues) but feel free to open them on the linter too and we can transfer them.

/fyi @bwilkerson

**Comment by bernaferrari** [comment]
Thanks! I recently opened https://github.com/dart-lang/sdk/issues/46025, but I was wondering where else these things could happen. There is also the request to auto-fix ';' somewhere. But there is not a "central table" like what you did here.

**Comment by bernaferrari** [comment]
I believe `avoid_renaming_method_parameters` could somehow have a quick fix or at least a better description? Even if it is not always enforced or behind an --aggressive flag.

Right now it is way too hard to fix these. Ok, I shouldn't rename, but what is the original name?
- If I command+click in @override, it takes to @override method.
- If I command+click in the function, it brings all usages, which is chaotic when it comes from Flutter framework.
- Some users might not even know about command+click.

The error description could include: "configuration -> path" so you know what to fix. And I wouldn't complain if it had a quick fix.

![image](https://user-images.githubusercontent.com/351125/126838414-9b85e48c-2ea9-4c83-92ec-bb7f294beb86.png)

**Comment by bwilkerson** [comment]
I agree, it should have a quick fix.

I also think that the message should be improved (but then I think that's true for many of the lints). In particular, it should include the name of the parameter from the overridden method so that even if the user is using an editor that doesn't support quick fixes they will know what name to use.

**Comment by pq** [comment]
As of https://github.com/dart-lang/linter/commit/a8a1e9752dc00dd5f4821a405fafc5930f9d566c, [lint rule docs](https://dart-lang.github.io/linter/lints/index.html) now include a badge indicating if a rule has an associated quick-fix.  For example:

![image](https://user-images.githubusercontent.com/67586/179293381-d7e5c1df-752e-4ba7-9125-32eed97e1152.png)

There's also a machine-friendly digest that can be consumed if we wanted to make a dashboard or otherwise process this data.  For that see: [linter/lints/machine/rules.json](https://dart-lang.github.io/linter/lints/machine/rules.json)

**Comment by devoncarew** [comment]
I believe this is now complete? I see that the lints docs on dart.dev - e.g., https://dart.dev/tools/linter-rules#avoid_empty_else - now show whether a lint has an associated quick fix (though, we may want to play with the presentation a bit - prefer to use a badge to indicate there's an associated quick fix, instead of just text?) .

Closing this as I believe this is done. cc @pq @parlough
