### ISSUE TITLE
Update the readme to clarify the goals and non-goals of this package

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/lints#121]
goals: supporting a recommendation for a core and recommended set of lints
non-goals: recommendations past that (e.g., 'strict')

---

In order to better make the community aware of linting sets beyond the recommended one here, we could consider listing commonly used community lint sets.

**Comment by parlough** [comment]
I mentioned this in https://github.com/dart-lang/lints/issues/102#issuecomment-1552039195, but:

> As for your mention of the community lint sets, we could consider suggesting use of a standard lints or linter-rules pub topic and linking to that topic.

**Comment by devoncarew** [comment]
> we could consider suggesting use of a standard `lints` or `linter-rules` [pub topic](https://dart-dev.web.app/tools/pub/pubspec#topics) and linking to that topic

Great idea! That would help w/ discovery of lints sets.
