### ISSUE TITLE
adding alt text for images in recommended

### ISSUE THREAD

**Issue by gregorscholz** [dart-lang/lints#133]
When creating an image widget, you should provide an alternative text which describes the image.
This can be achieved by adding a semanticLabel to images.
This can make the app more accessible for vision impaired users who are using screen reader.

**Comment by lrhn** [comment]
This is a Flutter-specific lint, so this request should probably be made to https://github.com/flutter/packages/tree/main/packages/flutter_lints

**Comment by gregorscholz** [comment]
But if i follow the link at the bottom of the readme to file a lint proposal i get forwarded to here.

**Comment by gregorscholz** [comment]
Oh ok, sorry, my bad!
