### ISSUE TITLE
SizedBox.shrink() is suggested

### ISSUE THREAD

**Issue by davidCcD** [dart-lang/lints#134]
**Describe the rule you'd like to see added and to what rule set**
hint: Container() shall be SizedBox.shrink()
hint: SizedBox() shall be SizedBox.shrink()

**Comment by devoncarew** [comment]
@davidCcD - thanks for the issue; I believe this is for a suggestion for a new lint? If so, this should be re-filed at dart-lang/linter; this repo is for managing the lint set that we recommend to dart users generally.
