### ISSUE TITLE
Consider adding `no_wildcard_variable_uses` to core

### ISSUE THREAD

**Issue by pq** [dart-lang/lints#139]
See: https://github.com/dart-lang/sdk/issues/51221

/fyi @munificent

**Comment by natebosch** [comment]
We can't come up with a meaningful name automatically, but would it be worthwhile to try to find a pattern to have a fix with an automatic rename to something non-meaningful (`localVar`, `argument1`) or semi-meaningful (maybe a heuristic on the type or something else)?

I think I lean towards not trying to add a fix, I can't recall what portion of our current core set has a fix.

**Comment by devoncarew** [comment]
This is approved for the `core` set.

**Comment by devoncarew** [comment]
This lint requires 3.1, which the package currently doesn't set as its minimum.
