### ISSUE TITLE
Remove `prefer_equal_for_default_values` from the `recommended.yaml` set

### ISSUE THREAD

**Issue by parlough** [dart-lang/lints#143]
Now that the package requires SDK `^3.0.0`, this lint does nothing since it's not reported by the Dart 3 SDK, which instead reports the [`deprecated_colon_for_default_value`](https://dart.dev/tools/diagnostic-messages#deprecated_colon_for_default_value) diagnostic for 2.12-2.19 language versions.

\cc @pq @devoncarew

**Comment by lrhn** [comment]
If we make the SDK requirement for that lint be `^3.0.0`, then it's definitely not needed.
If the same version of the lints package can be used by older SDKs, then it might be worth retaining, as long as we're sure that the lint doesn't cause double-reports in SDKs where the analyzer warns itself. (I guess that when the analyzer knows that it reports useing `:`, it can also know to ignore this lint.)

**Comment by devoncarew** [comment]
Removal approved.
