### ISSUE TITLE
Add `dangling_library_doc_comments` to core set.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/lints#148]
The existing lint [dangling_library_doc_comments](https://dart.dev/tools/linter-rules/dangling_library_doc_comments)
warns about library doc-comments that are not placed on a `library` declaration.

The dartdoc tool has historically treated doc-comments on the first import as a library comment, but it is a hack, and it's fragile. If someone removes the last import, the comment now becomes a comment on the first declaration of the library, and is not shown as library doc. There is no warning.

**Describe the rule you'd like to see added and to what rule set**
I'd add the `dangling_library_doc_comments` lint to *core*.
A mistake noticed by this lint can affect the public DartDoc of a package, so it's reasonable to apply it to pub packages.

**Comment by goderbauer** [comment]
I am in favor of adding this, it has caught some good-to-avoid issues with Flutter's doc.

**Comment by natebosch** [comment]
LGTM

**Comment by devoncarew** [comment]
This proposal is accepted.
