### ISSUE TITLE
forced var

### ISSUE THREAD

**Issue by bsz0206** [dart-lang/lints#162]
**Describe the rule you'd like to see added and to what rule set**
When 'var' can be used (not as Object/dynamic), it should not allow explicit  type declaration:

Example:
Bad:
  String a= "";
  Map m=<String, dynamic>{};

goog:
  var a="";
  var m=<String, dynamic>{};

**Comment by parlough** [comment]
Does the [`omit_local_variable_types `](https://dart.dev/tools/linter-rules/omit_local_variable_types) lint accomplish what you are looking for?

**Comment by parlough** [comment]
Oh sorry, you opened this issue in `package:lints`, not the linter repository itself.

I don't think `package:lints` will include this lint by default, as some users prefer to always explicitly type variables. You can always [enable extra lints yourself](https://dart.dev/tools/analysis#enabling-linter-rules) though in your project's `analysis_options.yaml` file or choose a [different prebuilt set](https://pub.dev/packages?q=topic%3Alints) which enables it by default.

**Comment by bsz0206** [comment]
I think I mentioned it in a wrong thread. I didn't know about omit_local_variable_types

**Comment by bsz0206** [comment]
I think I mentioned it in a wrong thread. I didn't know about omit_local_variable_types
