### ISSUE TITLE
Unwaited return for when Future is expected

### ISSUE THREAD

**Issue by bsz0206** [dart-lang/lints#163]
Unwaited does work only on void returns. We are forced to ignore, which is not nice:

FutureBuilder(
    // ignore: discarded_futures
    future: asyncCall(),

Unwaited does work only on void returns:
FutureBuilder(
    future: unawaited(asyncCall()),,

**Comment by devoncarew** [comment]
Thanks for the report; this repo is for proposals to add existing lints to our recommended lint set. You might want to re-file this at the dart-lang/sdk repo?

**Comment by bsz0206** [comment]
thanks. can you refer me to the page?
