### ISSUE TITLE
flutter_lints

### ISSUE THREAD

**Issue by HakeemAzman** [dart-lang/lints#169]
When I tried to test the app I was greeted with this error:

"Error Getting Packages" 
"Check the following custom dependencies: flutter_timer_countdown: ^1.0.6."
"Because [app_name] depends on flutter_timer_countdown ^1.0.6 which depends on flutter_lints ^2.0.0, flutter_lints ^2.0.0 is required.
So, because [app_name] depends on flutter_lints 3.0.0, version solving failed."

I believe the version 1.0.6 is still using flutter_lints ^2.0.0 and the current flutterflow uses flutter_lints ^3.0.0

**Comment by devoncarew** [comment]
I think this issue is best filed against `flutter_timer_countdown`; It'll either need to rev it dep on flutter_lints (or likely move the dep to a dev_dependency).
