### ISSUE TITLE
Potential issues with defined lints sets

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/lints#17]
I compared the lints listed in the yaml files here against my internal notes, and I'm seeing the following potential issues:

### Missing from this repo

* `always_declare_return_types`
* `unawaited_futures`

## Recommended lints

* `avoid_empty_else`
* `avoid_private_typedef_functions`
* `avoid_relative_lib_imports`
* `avoid_shadowing_type_parameters`
* `avoid_types_as_parameter_names`
* `await_only_futures`
* `camel_case_extensions`
* `camel_case_types`
* `curly_braces_in_flow_control_structures`
* `empty_catches`
* `file_names`
* `hash_and_equals`
* `iterable_contains_unrelated_type`
* `list_remove_unrelated_type`
* `no_duplicate_case_values`
* `non_constant_identifier_names`
* `omit_local_variable_types`
* `package_prefixed_library_names`
* `prefer_generic_function_type_aliases`
* `prefer_is_empty`
* `prefer_is_not_empty`
* `prefer_iterable_whereType`
* `prefer_mixin`
* `prefer_typing_uninitialized_variables`
* `provide_deprecation_message`
* `unnecessary_overrides`
* `unrelated_type_equality_checks`
* `use_rethrow_when_possible`
* `valid_regexps`
* `void_checks`

**Comment by mit-mit** [comment]
@pq @munificent @goderbauer are all these omissions intentional?

**Comment by devoncarew** [comment]
`unawaited_futures`, `omit_local_variable_types`, and `prefer_mixin` were removed from v1.0.0 as there's not yet full alignment on those (I believe some issues affected Flutter code that need to be addressed first). See https://github.com/dart-lang/linter/pull/2601/files

I don't have any info on the other recommended items. I assume this repo was mostly a straight copy from https://github.com/dart-lang/linter/tree/master/tool/canonical ?

**Comment by goderbauer** [comment]
Additionally, `avoid_private_typedef_functions` was removed in https://github.com/dart-lang/linter/pull/2517 after we agreed in a meeting that that lint is too narrow.

All the other lints you're listing under "Recommended lints" are actually part of the core.yaml set (https://github.com/dart-lang/lints/blob/1f80da49abf8b4ea15461e42ebb09eb51917b49d/lib/core.yaml), which is imported from recommended.yaml:

https://github.com/dart-lang/lints/blob/96ebfd81c4ad1846787bfeaac2e1966655b0a56c/lib/recommended.yaml#L1

So all the lints listed in the issue (with the noted exceptions of `unawaited_futures`, `omit_local_variable_types`, `prefer_mixin`, and `avoid_private_typedef_functions`) actually appear to be part of core.yaml/recommended.yaml.

**Comment by mit-mit** [comment]
> All the other lints you're listing under "Recommended lints" are actually part of the core.yaml set

Sorry, my bad, that was a flaw of the way I did my diff.

**Comment by mit-mit** [comment]
How about I close this issue, but open three new tracking issues for each of `unawaited_futures`, `omit_local_variable_types`, and `prefer_mixin`  ?

**Comment by pq** [comment]
> ... open three new tracking issues ...

That would be great.

**Comment by mit-mit** [comment]
Closing; we now have tracking issues for the four potential lints:

https://github.com/dart-lang/lints/issues/26
https://github.com/dart-lang/lints/issues/25
https://github.com/dart-lang/lints/issues/24
https://github.com/dart-lang/lints/issues/23
