### ISSUE TITLE
Determine default lint set for `dart create`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/lints#20]
We should make a final call regarding what set of lints `dart create` puts the user on. We currently use `core`, but that is inconsistent with `flutter create` which uses `recommended`

**Comment by goderbauer** [comment]
> but that is inconsistent with flutter create which uses recommended

`flutter create` uses `package:flutter_lints`, which is build on top of recommended. It doesn't have an equivalent to core.

**Comment by lrhn** [comment]
I think we should use `recommended`. After all, it's what we *recommend* that you use. You can still choose `core` if you want to, but `dart create` is allowed to be opinionated since you're free to change it afterwards.

**Comment by mit-mit** [comment]
Pedantic 1.8 has been the default for many Dart-only packages (as it's what pub.dev scores with). If we use recommended for the Dart default, then these lints are new to those coming from pedantic 1.8:

- always_require_non_null_named_parameters
- annotate_overrides
- avoid_function_literals_in_foreach_calls
- avoid_null_checks_in_equality_operators
- avoid_renaming_method_parameters
- avoid_returning_null_for_void
- avoid_single_cascade_in_expression_statements
- constant_identifier_names
- control_flow_in_finally
- empty_statements
- exhaustive_cases
- implementation_imports
- overridden_fields
- package_names
- prefer_adjacent_string_concatenation
- prefer_collection_literals
- prefer_conditional_assignment
- prefer_final_fields
- prefer_for_elements_to_map_fromIterable
- prefer_function_declarations_over_variables
- prefer_if_null_operators
- prefer_initializing_formals
- prefer_inlined_adds
- prefer_is_not_operator
- prefer_null_aware_operators
- prefer_spread_collections
- prefer_void_to_null
- unnecessary_brace_in_string_interps
- unnecessary_getters_setters
- unnecessary_string_escapes
- unnecessary_string_interpolations
- unnecessary_this
- use_function_type_syntax_for_parameters

That is a pretty long list, and more than I had initially imagined. But I think it's a good choice to use recommended as a default:

* It bring alignment between `dart create` and `flutter create`
* It's just a default; you can easily switch to core
* The template change will only affect new projects.

**Comment by mit-mit** [comment]
If we agree to go with `recommended`, then we should update the example in the readme to import that:
https://github.com/dart-lang/lints/blob/main/README.md#how-to-enable-these-lints

**Comment by pq** [comment]
+1 to `recommended`.

**Comment by mit-mit** [comment]
Updating in https://dart-review.googlesource.com/c/sdk/+/199482
