### ISSUE TITLE
Consider `depend_on_referenced_packages` for core lints inclusion

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/lints#42]
This is a new lint which hasn't shipped in the sdk yet but will in the next lint release.

What it does is ensure that you have a dependency (or dev dependency) in your pubspec if you import a package. There should be no valid situation where you import a package and don't depend on it in your pubspec, and there should be no false positives for this lint.

Not depending on a package but importing it means you are relying on it being available as a _transitive_ dep which is risky (it could disappear at any time). It also means that you have no dependency constraint on it and could be broken by the package if it has a breaking change.

Note that `pub lish` already warns about this and may negatively score already, so we would want to avoid a duplicate negative score - @jonasfj might know more about the existing behavior.

**Comment by jakemac53** [comment]
cc @natebosch @munificent @pq @mit-mit @lrhn

**Comment by mit-mit** [comment]
sgtm

@goderbauer wdyt?

**Comment by lrhn** [comment]
LGTM.
Do we have a "don't depend on unreferenced packages" lint too, to avoid dependencies that you don't need?
Or to ensure you don't have a dependency on something which should just be a dev-dependency?

**Comment by bwilkerson** [comment]
No, we don't. We can see when an import is referencing a package that isn't listed in the dependencies by examining two files. To catch the case where a dependency isn't referenced we'd need to analyze all of the files in the package. Neither the analyzer nor the linter are architected to make that efficient.

**Comment by devoncarew** [comment]
I think we can get good feedback before this is added to `lints`. That might look like:
- rolling the version of package:linter w/ the impl. into the SDK
- shipping a new beta SDK release
- emailing flutter announce about the lint / tweeting
- seeing if we get any issues reported

I think a lot of people will be interested in this lint - I'm sure we'll get some traction in a beta release. We could also validate through google3 for some of the lints.

**Comment by devoncarew** [comment]
For a lint which had been implemented for a while, I wouldn't have concerns about just adding it to the set of recommended lints. For a newly authored lint though, I think we want to find a few more click stops before turning it on for everyone.

**Comment by jakemac53** [comment]
> * emailing flutter announce about the lint / tweeting

Ya that is a good idea, I am not on social media really myself so I would have to rely on others for this.

> I think a lot of people will be interested in this lint - I'm sure we'll get some traction in a beta release. We could also validate through google3 for some of the lints.

Unfortunately this lint doesn't apply to google3, but in general ya that is I think a good strategy.

> For a lint which had been implemented for a while, I wouldn't have concerns about just adding it to the set of recommended lints. For a newly authored lint though, I think we want to find a few more click stops before turning it on for everyone.

Ya I definitely agree, not pushing back on the idea. What I actually want is just to figure out how to actually get it in the hands of people so we can get that validation we want :).

**Comment by goderbauer** [comment]
> @goderbauer wdyt?

I think this lint would be a good addition.

I also agree with @devoncarew that we should wait a little until the lint has matured a little. We should also enable it for the flutter repositories (flutter/flutter, flutter/engine, flutter/packages, flutter/plugins) and verify that it doesn't cause any issues there.

**Comment by jakemac53** [comment]
This should likely be blocked on fixing https://github.com/dart-lang/linter/issues/2694

**Comment by mit-mit** [comment]
Approved assuming we fix https://github.com/dart-lang/linter/issues/2694 first

**Comment by pq** [comment]
We should investigate.  I'm not 100% sure if we have enough information to generate a sensible version constraint (though I guess we could default to `any` with a TODO to tighten?)

/fyi @bwilkerson

**Comment by jakemac53** [comment]
Not sure if you can run pub commands, but you could just do `pub add <package-name>`. That just adds a `^` constraint on the latest version afaik, but its fine for most use cases and its the "safe" thing to do.

**Comment by jonasfj** [comment]
Calling `dart pub add` would be ideal, as it will create `^a.b.c` constraint on the latest version compatible with your SDK and other dependencies. This reduces risk that you get a conflict.

But last I talked to @bwilkerson about it, we would likely have to give `dart pub add` a dry-run mode with machine readable output, so that the diff can be sent over the LSP.

But maybe just adding `^a.b.c` for the latest version is fine.

**Comment by jakemac53** [comment]
> latest version compatible with your SDK and other dependencies.

Oh nice I didn't know that was this smart 👍

**Comment by pq** [comment]
So we do call pub apis for completions (see [`PubPackageService`](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/pub/pub_package_service.dart#L138)) and the results it provides should be consistent with `pub outdated` which *I think* ensures version compatibility?

**Comment by jonasfj** [comment]
> So we do call pub apis for completions (see PubPackageService) and the results it provides should be consistent with pub outdated which I think ensures version compatibility?

`pub outdated` won't have versions for packages not added yet :D

But I could be convinced to add a `--dry-run --json` options to `dart pub add`.

**Comment by srawlins** [comment]
If this lint is reported, but errors are not present, then the package is available as a transitive dep. This should mean it is available in PubPackageService.cachedPackages, yes? So using this info we could add `depName: ^version.already.in.use` to the pubspec.

We could also just add `depName: any`.

We could also wait for `dart pub add --dry-run --json`.
