### ISSUE TITLE
README links to anywhere but this package's list of lint rules

### ISSUE THREAD

**Issue by srawlins** [dart-lang/lints#50]
The README has a couple links to articles on pub.dev regarding static analysis or lint rules at large, but not the two lists of lint rules. I think that'd be a great addition.

**Comment by mit-mit** [comment]
Thanks for the suggestion. Just to confirm, the two lists you mention are these?

1. https://dart.dev/guides/language/effective-dart/style
1. https://dart.dev/tools/linter-rules

**Comment by srawlins** [comment]
Sorry, I meant a link to:

* https://github.com/dart-lang/lints/blob/main/lib/core.yaml and
* https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml

**Comment by devoncarew** [comment]
Related to https://github.com/dart-lang/lints/issues/128.

**Comment by devoncarew** [comment]
Largely addressed in #129.
