### ISSUE TITLE
Consider adding `unnecessary_late` to recommended

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/lints#61]
Do not use late when it doesn't change semantics to reduce mental overhead. Maybe too new for inclusion (submitted in December 2021). Needs to be tested in Flutter.

**Comment by goderbauer** [comment]
Unfortunately, there's no auto-fix for it, but it looks auto-fixable.

**Comment by pq** [comment]
> Unfortunately, there's no auto-fix for it

FWIW and as a general rule, we'll prioritize fixes for lints that adopted here so this may just be a temporary inconvenience.

**Comment by goderbauer** [comment]
Sounds good. I think it would be a good requirement for the lints packages that newly added lints have to come with an auto-fix if they are auto-fixable. That will make it easier to move to newer versions of the packages.

**Comment by parlough** [comment]
I will implement the quick fix for this once the lint is improved to properly target the keyword: https://github.com/dart-lang/linter/pull/3153

**Comment by srawlins** [comment]
Sorry, @parlough I didn't see you volunteer. This one is also done.
