### ISSUE TITLE
Consider adding `use_decorated_box` to flutter_lints

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/lints#62]
Similar to `sized_box_for_whitespace`. Use Decoration over Container as a more light-wight alternative. Enables more const widget trees. Need to check impact on Flutter's code base.

**Comment by goderbauer** [comment]
Doesn't have an auto-fix, but it looks auto-fixable.

**Comment by goderbauer** [comment]
I tried this out on the Flutter codebase and I am not convinced that this is a clear win. It sometimes requires some awkward refactoring and rarely leads to more const widget trees in practise. It's an interesting lint for the more experienced flutter developer, but I don't think we should enable this by default.

**Comment by BaranMichal25** [comment]
Related https://github.com/flutter/flutter/issues/101631
