### ISSUE TITLE
Consider adding `unnecessary_nullable_for_final_variable_declarations`

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/lints#67]
Cleaner code, less mental overhead. Enabled in Flutter.

**Comment by mit-mit** [comment]
Need to fix metadata:

```
Maturity: experimental
Linter v0.1.118
```

**Comment by mit-mit** [comment]
Approved assuming this is only for local variables.

**Comment by pq** [comment]
Currently it *does* cover fields and top-level variable declarations in addition to locals.

For fields, would it be sufficient to update it to skip the override case?

/cc @lrhn

**Comment by srawlins** [comment]
This has a fix.
