### ISSUE TITLE
Consider adding `prefer_interpolation_to_compose_strings`

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/lints#70]
Produces more readable code. Spreads awareness for interpolation. Enabled in Flutter.

**Comment by mit-mit** [comment]
Approved with the assumption that we can loosen the lint to only fire when there is a mix of string literals and variables being combined with `+` (e.g. `'foo' + bar` is disallowed, `a + b` or `'foo' + 'bar'` is not).

**Comment by srawlins** [comment]
This has a fix.

**Comment by pq** [comment]
Cheers @srawlins!
