### ISSUE TITLE
add sort_constructors_first to flutter_lints

### ISSUE THREAD

**Issue by amanv8060** [dart-lang/lints#76]
Flutter Github Wiki states that [constructors come first in class](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#constructors-come-first-in-a-class). 
We already have lint that enforces the same [link](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).

So can this lint be added to the flutter_lints package?

[This issue](https://github.com/dart-lang/sdk/issues/45812) has some discussion related to it. 

[Upstream Issue](https://github.com/flutter/flutter/issues/100996) which tracks the addition of this lint.

cc/ @goderbauer

**Comment by natebosch** [comment]
Note that Flutter style guides is intended to apply only to the flutter repo and uses styles that don't match the Dart team's recommendations. This specific lint does not go against any recommendations and it would be OK to consider including it, but the fact that it matches the Flutter repo specific style guide isn't a factor I think we should consider for inclusion of lints.

For this lint specifically I lean towards not including it in either `lints` or `flutter_lints`.

**Comment by goderbauer** [comment]
I agree with @natebosch and also think that we shouldn't include it in the packages. People should of course feel free to enable it in their own projects, though, if they like the style.

**Comment by devoncarew** [comment]
Thanks for the proposal! Closing as it doesn't look like we're going to take action on it.
