### ISSUE TITLE
`discarded_futures`

### ISSUE THREAD

**Issue by Kimiguro** [dart-lang/lints#83]
Hi, linter 1.25 have discarded_futures. Can you add this lint in next release?

**Comment by lrhn** [comment]
This lint seems either under-specified or overly aggressive, and it's probably misleading to force it on users.

The documentation at https://dart-lang.github.io/linter/lints/discarded_futures.html states that you should not call asynchronous functions in non-`async` functions *at all*. No exceptions, no workarounds, no allowances for actually handling the resulting `Future`, like the `unawaited(asyncFunction())` allowed by the `unawaited_futures` lint.

> Making asynchronous calls in non-**async** functions is usually the sign of a programming error. In general these functions should be marked **async** and such futures should likely be awaited (as enforced by **unawaited_futures**).
>
> **DON'T** invoke asynchronous functions in non-**async** blocks.

That is not something I'd recommend in general, and not something I'd follow myself. There are too many perfectly reasonable reasons for calling an `async` function and working directly with the `Future`, if you know what you are doing.

A lint that applies the same rules for *handling* futures in non-`async` functions that `unwaited_futures` applies to `async` functions would be reasonable. The goal is to not forget to handle a future.

Forcing all uses of futures to be in `async` functions is too strong a requirement.

**Comment by eernstg** [comment]
Perhaps that lint should be renamed to something like `use_async_with_futures`, based on the fact that it pushes developers in the direction of using `async` function bodies whenever they call a function that returns a future (which is nearly the same thing as "whenever they're using a future").

**Comment by devoncarew** [comment]
After discussion, we think this lint has too many false positives to add to package:lints. We may however investigate improvements to `unawaited_futures` to make it a feasible lint to add, and or creating a lint to act like `unawaited_futures` but for non-async functions.
