### ISSUE TITLE
Add `use_string_in_part_of_directives`

### ISSUE THREAD

**Issue by srawlins** [dart-lang/lints#85]
I hereby propose we add [use_string_in_part_of_directives](https://dart-lang.github.io/linter/lints/use_string_in_part_of_directives.html).

* The rule is part of Effective Dart.
* The language team is considering banning the old syntax in a future version of Dart.

**Comment by devoncarew** [comment]
As part of `core`? `recommended`?

**Comment by srawlins** [comment]
I propose for `core`.

**Comment by natebosch** [comment]
yes, I vote `core`. If we could do it for free we'd probably eliminate non-string directives at the language level.

**Comment by devoncarew** [comment]
Approved for `core`.
