### ISSUE TITLE
Add `use_string_buffers` to the `core` or `recommended` sets

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/lints#90]
Using string buffers instead of `+=` can save _a lot_ of time and space, as seen in this issue: https://github.com/dart-lang/sdk/issues/50304. `StringBuffer` isn't necessarily ubiquitous, so the lint that tells you to use it should be enabled by default, either in `core` or `recommended`.

**Comment by natebosch** [comment]
I worry a bit about recommending this one. The false positives may be rare, but I like to avoid lints with legitimate false positives that don't have any other mechanism than an `// ignore`. https://github.com/dart-lang/linter/issues/2159

I know @kevmoo is a fan of this lint. It does help more often than it hurts.

**Comment by kevmoo** [comment]
It keeps folks from using `myString = myString + 'more stuff';` – which has HORRIBLE performance implications in Dart (I forgot who recently talked about how V8 has special hacks for this – @mraleph ?)

**Comment by kevmoo** [comment]
Ha! It was the referenced issue. 🤦

**Comment by kevmoo** [comment]
Short version: yes, I'm a fan.

I think `// ignore` is fine for one-offs. it forces folks to document why they avoid the best practice IMHO

**Comment by devoncarew** [comment]
After discussion, we think this lint will have too many false positives to add to package:lints. We would want this to only trigger for performance sensitive sections of code, but its not clear how we could successfully lint for that.
