### ISSUE TITLE
handle `prefer_equal_for_default_values` deprecation in 2.19

### ISSUE THREAD

**Issue by pq** [dart-lang/lints#92]
In 2.19.0  (as of https://github.com/dart-lang/sdk/commit/289aa509cd4f078457faf50670bb2871c31b2718), analyzer produces a warning when colons are used for default values.  This makes `prefer_equal_for_default_values` redundant and slated for deprecation (https://github.com/dart-lang/linter/pull/3855).  

I plan to cherry-pick a linter that doesn't produce a lint for SDKs `>= 2.19.0-0` so we won't double-report but we should still remove this lint from the recommended set.  Is it worth a `package:lints` release that _only_ removes this lint for SDKs `>= 2.19.0-0`?  Other considerations?

/cc @bwilkerson @mit-mit @munificent @natebosch @jacob314 @jakemac53 @lrhn @devoncarew @goderbauer

**Comment by natebosch** [comment]
Seems fine to release.

It might also be a good reason to evaluate if there are new lints we should include. `implicit_call_tearoffs` is worth including right away.

**Comment by bwilkerson** [comment]
The one consideration I can think of is that if we release a new version of the lint set, and a user moves to the new version without also moving to 2.19, they will lose coverage.

**Comment by jakemac53** [comment]
Generally SGTM, if we do increase the min sdk to 2.19 we should just keep in mind that means users on older SDKs won't get any new lint sets. If we don't increase it then as brian says we lose some coverage on the lint.

I would probably suggest moving to a min sdk of 2.19, but I don't know when stable of that is slated for release. If it isn't soonish then we might want to hold off, or make sure we do an earlier release with a last set of changes to the lints that we want people to get prior to 2.19 stable.

**Comment by mit-mit** [comment]
>  don't know when stable of that is slated for release

Roughly end of January 2023, is the current plan

**Comment by devoncarew** [comment]
@pq - is this complete?
