### ISSUE TITLE
Add `enable_null_safety` to core

### ISSUE THREAD

**Issue by srawlins** [dart-lang/lints#97]
This rule: https://dart-lang.github.io/linter/lints/enable_null_safety.html

I propose we add it to a lints release that supports Dart 2.x, so that users can see if they have any pre-null safety files they forgot about, before using Dart 3.0 (like tests, tools, etc).

**Comment by srawlins** [comment]
CC @bwilkerson @pq as I _think_ this is the only diagnostic which can report a `// @dart=2.9` language version override in Dart 2.19.

**Comment by pq** [comment]
SGTM.

/fyi @natebosch @jakemac53 @mit-mit @lrhn @goderbauer @munificent

**Comment by lrhn** [comment]
If we make the `lints` package require SDK 2.19, it should not unduly affect code that still uses older SDKs.
Would we want that?

**Comment by srawlins** [comment]
I don't see anything wrong with keeping the minimum SDK version at 2.17.0.

**Comment by devoncarew** [comment]
FYI that we've since increased the min. required sdk here to 3.0, so if we do want this to resolve into a pre-3.0 sdk, we'd need to publish a release off the commit for `package:lints` `v2.0.1`.

**Comment by devoncarew** [comment]
From a discussion, this would have been useful to add a few SDK releases ago, but will add little to no value at this point. Closing.
